# Generated by Django 5.0 on 2024-03-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_answerhistory_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isRigged',
            field=models.BooleanField(default=False),
        ),
    ]
