# Generated by Django 5.0 on 2024-03-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_user_isrigged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isRigged',
            new_name='is_rigged',
        ),
    ]
