# Generated by Django 5.0 on 2024-03-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_isrigged_user_is_rigged'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rigword',
            field=models.CharField(default='', max_length=1023),
        ),
    ]
