# Generated by Django 5.0 on 2024-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_question_rigword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='machineused',
            field=models.IntegerField(default=0),
        ),
    ]
