# Generated by Django 5.0 on 2024-03-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_machineused_user_machine_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='righints',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
